### ISSUE TITLE
bug: A JavaScript error occurred in the main process

### ISSUE THREAD

**Issue by codefreak558** [0neGal/viper#104]
**Describe the bug**
I am unable to launch the Viper launcher.

I just gives me a javascript error when I launch it I have reinstalled the launcher and that didnt fix the issue.

![image](https://user-images.githubusercontent.com/46318596/160236345-6a8933be-463b-46bd-8b60-31d0b86c4ce9.png)

**Comment by 0neGal** [comment]
Given that this provides little to no information whatsoever, there's no way to reproduce this, nor is there any way to diagnose it. I would urge for you to try the portable build of Viper, and see if that makes a difference. Otherwise there's not much I can do, and I will close this issue unless someone finds a way to reproduce it.
