### ISSUE TITLE
Discuss collaboration

### ISSUE THREAD

**Issue by Alystrasz** [0neGal/viper#12]
There's an ongoing discussion on discord (northstar-installer-talk thread) about modding and installers in general.

Let's focus on one piece of software instead of several.

**Comment by 0neGal** [comment]
I've been silently overviewing some if this discussion actually, but since I am not, and probably never will be a big fan of Discord I've done so on a temporary account, hence why I haven't interacted with it.

This mainly comes back to when Discord banned my account for using a third-party terminal client, then unbanned it, and kept my phone number banned so I still can't use that account, but that's irrelevant.

As for how to do collaboration, either just do everything through GitHub, or if Bob sets up a Matrix bridge for Discord I can simply join that way of course. I do think the very scattered way of development that all these launchers/updaters have right now isn't the best... And should be improved lol

I am currently in the midst of making a man page (will commit soon), after that I will have a go at doing mod managing so Viper will be more than just updating+launching Northstar. I took a crack at trying to get the `electron-updater` to work yesterday, tho I must say I've never used it before and was very much just doing random things, so if somebody wants to take a better look at that, that'd be awesome, it's over on the `auto-updater` branch.

And of course feel free to make PR's and I'll have a look at them, and merge them and so on. As for the mods it'd be lovely if 23Carrot were to make a web API, that way we can do not just local mod managing but also download them etc...

**Comment by 0neGal** [comment]
Given that I just pushed the man page, I'll be starting to work on the whole mod installer etc... Albeit just locally, since there's no official or unofficial API for mods... :p

**Comment by 0neGal** [comment]
> Woshi: so far: i think a progress bar would be very handy
> i got no clue if it's doing anything rn

I wanna point out the release you gave them was pretty outdated, and the newest one, while it doesn't have a progress bar it does show what it's doing in the GUI

**Comment by Alystrasz** [comment]
You really should participate in the chat :p

**Comment by 0neGal** [comment]
I frankly cannot, I have no way of making an account. My phone number is blocked for unknown reasons.

**Comment by 0neGal** [comment]
> I'll be starting to work on the whole mod installer etc

Even tho this isn't an issue at all related to mods, this is the current progress on it, feel free to share it in the Discord. It'll likely end up being a drop-down of some kind as to not confuse newer and potentially less experienced users.

![](https://user-images.githubusercontent.com/33325154/147787588-4d6a2b82-0d5d-4248-93f1-e2c9775f8d4f.png)

Besides this we'll also have `--mods`, `--installmod`, `--removemod` and so on. Which will both have a `=all` argument.

**Comment by Alystrasz** [comment]
Yeah, this should be discussed on a separated issue.

And you really should find a way to participate on Discord 😁

**Comment by Alystrasz** [comment]
btw, what do we need before creating first release?

I'm thinking:
* auto-update
* full mods support
* bug fixes

Actually, we can release as soon as we have auto-updating 100% working, so we could add new features afterwards and have them deployed automatically

**Comment by 0neGal** [comment]
> btw, what do we need before creating first release?

Auto-updating. However, I doubt we get that done before mod support, as that's what I'm focusing on, so unless you can finish the auto-updating first, mod-support will probably already be a thing by then.

In case you or somebody else does finish it we will simply do a v0.9.0 release, and make v1.0.0 the full release with mod-support.

**Comment by Alystrasz** [comment]
Let me work on auto-updating then :)

**Comment by 0neGal** [comment]
[The first release is now out](https://github.com/0neGal/viper/releases/tag/v0.9.0)

If someone could test and verify that the Windows versions just as well without issues as the Linux versions that'd be amazing, but otherwise, our first release has now arrived, however missing mod support which will be added soon, Viper is now *"available to the masses"* if you will! 

I still have many features, changes and alike that I want to make so Viper should have many more releases in the future! Also @Alystrasz, if allowed could you post about the release in #mod-manager-news on the Discord...

**Comment by Alystrasz** [comment]
I unfortunately don't have rights to chat in this channel.
On the other hand, please create issues for all features/changes you would like to implement, so that pull requests can be made :)

**Comment by 0neGal** [comment]
> I unfortunately don't have rights to chat in this channel.

That is unfortunate, I wasn't quite sure whether it was only for Juicy, and their tool or everybody who makes updater/launchers...

> On the other hand, please create issues for all features/changes you would like to implement, so that pull requests can be made :)

I've been neatly writing down things on a list, and was planning on making issues for them soon, so it was already planned actually, I'm just slow lol.

**Comment by Alystrasz** [comment]
> I've been neatly writing down things on a list, and was planning on making issues for them soon, so it was already planned actually, I'm just slow lol.

Once you're done creating issues for all tasks, I suggest closing this issue and creating a GitHub project to better view what needs to be done before public release.
