### ISSUE TITLE
I cannot launch vanilla Titanfall through Viper. I go to the vanilla one, click it, and then bam it launches the Northstar version.

### ISSUE THREAD

**Issue by Nightshade2142** [0neGal/viper#143]
Title. I am running the latest version of Viper, Northstar, and vanilla. I don't know why this is happening. 

In launch options for Steam I just left it blank and in viper it's "-multiple"

In the viper launcher, where you choose which version you want to launch, it differs vanilla and Northstar but both launch options end up with Northstar.

**Comment by 0neGal** [comment]
Please don't make an issue and then delete the entire bug report template.

As for the problem, please make sure you didn't modify `Titanfall2.exe`, some guides recommend renaming it, and then making a duplicate `NorthstarLauncher.exe` and then renaming it to `Titanfall2.exe` meaning both programs launch Northstar.

Doing that, obviously results in both programs launching Northstar, as mentioned.

Besides that, I can't help much as this shouldn't be possible any other way, Viper launches `Titanfall2.exe` when attempting to run vanilla.

If you can find steps to reproduce the issue then I can actually help here, otherwise, with you being the only person with this I'd say it's more likely you accidentally did something wrong.

Hope that helps...

**Comment by Nightshade2142** [comment]
I solved the problem it was something else, thanks for helping though.
