### ISSUE TITLE
bug: Failure to install mods

### ISSUE THREAD

**Issue by M3TTA** [0neGal/viper#169]
When attempting to install some mods, the installation failed and this error message was displayed.
`An unknown error occurred while trying to install the mod. This may be the author's fault, and it may also by Viper's fault.`

The mods I got this error on.
[ProvoxinRGB](https://northstar.thunderstore.io/package/H0L0/ProvoxinRGB/)
[Cat Ears Grapple Pilot Female](https://northstar.thunderstore.io/package/Northstar_Archive/Cat_Ears_Grapple_Pilot_Female/)
[Speech Bubbles](https://northstar.thunderstore.io/package/Khalmee/Speech_Bubbles/)
[Team Loadout Viewer](https://northstar.thunderstore.io/package/Khalmee/Team_Loadout_Viewer/)

**Comment by gledinski** [comment]
Also facing this issue, either through a .zip file or from the "Find Mods" menu presents an error.
![image](https://user-images.githubusercontent.com/56172613/213942966-bc5ab4ef-4a87-4f4f-af5c-6f0469df7d96.png)

**Comment by GeckoEidechse** [comment]
> [ProvoxinRGB](https://northstar.thunderstore.io/package/H0L0/ProvoxinRGB/)

Has comments in its `mod.json` which Viper should be able to handle IMO by just parsing it as JSON5

> [Cat Ears Grapple Pilot Female](https://northstar.thunderstore.io/package/Northstar_Archive/Cat_Ears_Grapple_Pilot_Female/)

idk what the issue here is, the mod seems fine

> [Speech Bubbles](https://northstar.thunderstore.io/package/Khalmee/Speech_Bubbles/)
> [Team Loadout Viewer](https://northstar.thunderstore.io/package/Khalmee/Team_Loadout_Viewer/)

the `mod` folder inside has the first character uppercase, i.e. `Mod/`. I'll notify the author.

**Comment by 0neGal** [comment]
Actually this is fixed in the upstream build already, I've just yet to release a version with all the current fixes, it is planned to come out very soon, I just have a few small tidbits I'd like to include in the release first.

If you need the fix right now, then you can download the current upstream [Windows builds](https://github.com/0neGal/viper/suites/10414026051/artifacts/514595960) or [Linux builds](https://github.com/0neGal/viper/suites/10414026051/artifacts/514595959), I've yet to test this, but ideally the versions with auto update should update automatically to the latest release once it comes out.

I'll be closing the issue due to all this, but if you've further issues or remarks feel free to comment/re-open it. :)

**Comment by glebinski** [comment]
Thank you for bringing an update regarding this
