### ISSUE TITLE
feat: Install d3dcompiler DLLs automatically on Linux

### ISSUE THREAD

**Issue by L8zin** [0neGal/viper#188]
**What feature would you like added?**
On Linux there is an issue where the EA App is blank and therefore unusable. This makes it difficult to actually launch the game through Northstarproton. The official troubleshooting step for this is to install the runtime libraries d3dcompiler_43 and d3dcompiler_47 through protontricks/winetricks. Since this step is basically a necessity, shouldn't it be done automatically by the installer?

**Why should this feature be added?**
It would massively simplify the install process for a lot of people, including myself. Installing them through Protontricks can be quite the hassle. 

**Additional Info**
I don't know if this is doable due to licensing, but it might be possible to work around this by simply prompting the user to install it through protontricks automatically.

**Comment by 0neGal** [comment]
I've not experienced this myself, albeit, I haven't reinstalled the game in ages, and have never even used NorthstarProton...

Is this only an issue on NorthstarProton? And if not, is it a requirement/fixed in upstream Proton/Wine, or do some distros not ship the right version by default?

But yes, we could easily run a `protontricks` or `winetricks` install command to solve this, we'd however have to detect and use the right one, not just of those two, but whether to use Flatpak `protontricks` or the regular one. Which might be cumbersome.

If this is just a case of a bug that's fixed upstream, it may be far easier and a better solution to simply wait it out, as this would basically have to go along with #116, which isn't being merged any time soon, due to various reasons.

**Comment by L8zin** [comment]
My understanding of it is that this version cannot be shipped with Proton/Wine since they can't distribute actual windows libraries, only reverse-engineered ones. 

I've tested this again and yes, it only seems to happen with NorthstarProton. I will try to gather some more information and reach out to the developers of that instead. I still don't know if its possible to include this in the proton prefix but I will look into that. 

Proton/Wine _should_ detect if these files get added to the same directory as the executable, which is why i though that this would most easily be done through Viper.

**Comment by Jan200101** [comment]
This hasn't been an issue since NorthstarProton was rebased onto GE-Proton
