### ISSUE TITLE
Viper starts without game path

### ISSUE THREAD

**Issue by Alystrasz** [0neGal/viper#22]
Viper should not start as long as the user didn't provide Titanfall path.

Crash scenario:
1. Start Viper
2. When asked for game path, close window
3. Invoke any method that uses game path

![no_path_start](https://user-images.githubusercontent.com/11993538/147965071-45df345e-791e-4eee-847a-4ce4311ee075.gif)

**Comment by 0neGal** [comment]
What would you recommend to fix this? We could just disable the buttons if we had to. Perhaps make a function to get the game path instead of having it as a variable. Then in that function check if it is even set, if not `return false` and then build in a way to handle that on the frontend.

Again I don't know what more is needed than all buttons but the game path one being disabled, perhaps we can also `winLog()` an error saying the game path was invalid, along with that we should build in a way to check if the game path is still a valid game path when Viper launches/the game path function is used.

Furthermore! We should probably also do some verifying that the gamepath is actually a Titanfall game path. Aka checking for various files.

**Comment by Alystrasz** [comment]
Currently, viper interface appears in the same time as game path dialog, I think we should not display viper while we don't have a valid game path.
If a wrong path (or no path) is selected, we display an error message in a dialog and exit.

**Comment by 0neGal** [comment]
We'll just not call `start:index.js` if it's not set. However given that it gets executed along side the dialog code, maybe just make the start function run on an event, then call that event when a path has been selected, or you already have a valid path.

**Comment by Alystrasz** [comment]
You can assign me on this, I'll see what I can do.
