### ISSUE TITLE
bug: Viper does not launch in foreground

### ISSUE THREAD

**Issue by GeckoEidechse** [0neGal/viper#236]
**Describe the bug**
Taken from a recent ticket on Northstar Discord

> 
> **Describe your issue for us.**
> Whenever I try to launch Viper I can see it in task manager as a background process. It does not come up as a window.
> 
> **Have you read the Wiki and announcements?**
> Not everything (I have looked at faqs relating to northstar/viper as well as looking on reddit)
> 
> **What OS? What Installer (Viper/VTOL/R2MM)?**
> Windows 10/Viper
> 
> **Are you trying to host a server?**
> no
> 
> **What have you tried so far?**
> I have tried reinstalling viper
> Running the setup and app as an admin
> Restarting PC 
> Running TF2 with viper also running (had no reason for it to work but I tried it)
> 

![image](https://github.com/0neGal/viper/assets/40122905/dcda9427-a446-4545-ab17-d16d2a9861a5)

**Comment by 0neGal** [comment]
Sounds a lot like #231 albeit it got fixed, and they're presumable on the latest version. So it's likely just some other error that occurs before the window is created. I would need logs to diagnose this unfortunately :p

**Comment by GeckoEidechse** [comment]
I'll forward

**Comment by GeckoEidechse** [comment]
> ran it a third time and it had the same output as the second one `@Gecko`

![image](https://github.com/0neGal/viper/assets/40122905/90055c3f-45cf-46fb-8f9d-14725a81fdc7)

![image](https://github.com/0neGal/viper/assets/40122905/04bbdee1-63d0-462f-bc8d-351112421f19)

**Comment by 0neGal** [comment]
Seems to be an issue with parsing the `libraryfolders.vdf` file from Steam, while it's fixable without, I wouldn't mind knowing the contents of it (should be at `C:\Program Files (x86)\Steam\steamapps\libraryfolders.vdf`), wondering whether it's Viper's fault or the parser. Either way I'll add some more checking to it to fix this.

In the meantime, this could be fixed by either editing the config file (`%APPDATA%\viper.json`) manually and setting the path, or simply adding `--setpath "<gamepath>"` onto the `Viper.exe` command.

Replacing `<gamepath>` with the actual gamepath of course.

**Comment by 0neGal** [comment]
This should ideally be fixed with [`384977d`](https://github.com/0neGal/viper/commit/384977de2f89cdd26e15adc1f274bf46b3c7a03e)

**Comment by GeckoEidechse** [comment]
Seems to still be an issue in `1.12.0`

![image](https://github.com/0neGal/viper/assets/40122905/437327bd-7faf-452d-88ba-38d29ba73f5d)

**Comment by 0neGal** [comment]
Ouch, I now realize the actual issue, should be properly fixed in [`v1.12.1`](https://github.com/0neGal/viper/releases/latest)
