### ISSUE TITLE
Localisation

### ISSUE THREAD

**Issue by Alystrasz** [0neGal/viper#4]
If Bob validates this launcher, we should put some effort into translating it.

**Comment by 0neGal** [comment]
I'll work on a system to implement localization easily... I'm thinking just a JSON file with keys like `"message.welcome"` and then it's value, we could probably use the `Navigator.language` to automate it so the user doesn't have to select it.

Then save the language value so it's also available in the cli version.

**Comment by Alystrasz** [comment]
No need to reinvent the wheel, since Electron is used, we could use a npm package such as https://www.npmjs.com/package/i18next

**Comment by 0neGal** [comment]
I've never worked with this package before, and I'm not sure how it'd work with both the CLI and GUI, likely just because I don't know how to use this package. I also personally don't think our own way of doing localization would be hard to make or anything, but if it ends up being even easier to use i18next, then we can do so.

**Comment by 0neGal** [comment]
I've made a new branch (localization), with my own attempt at localization, feel free to give feedback and tell me if i18next could make it any easier.

**Comment by Alystrasz** [comment]
Neat!
Looks like we don't need additional packages after all!

**Comment by Alystrasz** [comment]
Implemented with 4abe10aebdfa06c9b9c31c98f084d511e3e2e319.
