### ISSUE TITLE
Northstar update process

### ISSUE THREAD

**Issue by Alystrasz** [0neGal/viper#5]
Before updating local Northstar version, we should check if the latest available version is not already installed (do we have a way to check local Northstar version?).
If a newer version is available online, I'm not sure whether we should download and install it automatically, maybe we should ask for user approval?

**Comment by 0neGal** [comment]
We could do a md5sum of the `northstar.zip` which is left inside the game folder after extraction, however, we'd still need a the md5sum of the release zip... Which GitHub doesn't provide (from what I know).

Another alternative is instead of using md5sums we can use the size of the zip, the likeliness two versions have the same size is there, but it's probably small. But given there's no way to check the currently installed version since Northstar doesn't provide a version file, we can't do much on that front.

The only other option is adding a file ourselves, so on install fetch the release version and save it in `ns-version.txt` or similar then compare it to the newest, this would mean however for the first time user if they already had Northstar installed we'd have to assume it's outdated.

Personally the last option seems like the best idea, currently. That is until Northstar provides something official. There's already an [issue over on the NorthstarLauncher repo](https://github.com/R2Northstar/NorthstarLauncher/issues/2) that discusses including a version number, I've already commented a bit in it.

**Comment by Alystrasz** [comment]
I agree, last option is the best we can do until there's an officially supported way to check Northstar version.
I'll work on this and see what I can do.

**Comment by 0neGal** [comment]
Probably just look into storing the `tag_name` inside the GitHub API request that we do in `update()/utils.js` inside a file.

And probably remove the "v" part of the tag name, preferably with replace so if Bob decides to change tag names it still works just fine :), it'll probably also make parsing the version number easier.

[(for reference here's the JSON output)](https://api.github.com/repos/R2Northstar/Northstar/releases/latest)

**Comment by 0neGal** [comment]
Another idea is just saving the number and checking if the `tag_name` for the latest release is the same or not. Either will do, and one doesn't require parsing the name in any way... So it's probably a better idea...
