### ISSUE TITLE
feat: mods auto-updating

### ISSUE THREAD

**Issue by Alystrasz** [0neGal/viper#79]
**What feature would you like added?**
Since Thunderstore provides mods versioning, Viper should be able to update installed mods if updates are available.
This behaviour should be configurable, for example CLI/server users may want to fix mods versions they use.

**Why should this feature be added?**
Get mod updates as soon as they're available: all fixes/new content is automatically installed.

**Comment by 0neGal** [comment]
I specifically and intentionally did not implement this, as I easily could've. Not only would this cause quite a bit of network traffic since it's not unlikely 5-10 mods are outdated especially if you've many mods, but it would also cause lag on the users end when all those mods are being updated.

Even more importantly is, since we currently overwrite every file when installing a mod, that means removing config files as well, unless Northstar makes it standard to have config files outside of the main mod folder there's not an easy way to fix this.

It'll just end up with unintentional confusion on the users end. At least that's my perspective.

**Comment by Alystrasz** [comment]
I don't think updating mods would cause lag when updating mods; while parsing package API, you'd directly find out which mods need to be updated, and those don't have such a big weight.

Configuration files are still an issue though. Didn't we talk about diffing files, not to delete configurations?

**Comment by 0neGal** [comment]
I'll try and have a look at it, another issue with config files is, what if a mod adds a new setting? That setting won't get auto added because that'd overwrite the config file.

**Comment by Alystrasz** [comment]
We'd have to merge old config file and new config settings.

**Comment by GeckoEidechse** [comment]
An update check and option to update right in the mods view would maybe be a nice alternative.

![image](https://user-images.githubusercontent.com/40122905/176997521-207ff60c-e142-441b-9dec-c0a3ef55109e.png)

Right now, in order to update a mod from within Viper, one has to:

1. Go to mods view
2. Click on _Find Mods_
3. Search for the mod they already have installed
4. Click on _Reinstall_
5. Profit

**Comment by 0neGal** [comment]
> An update check and option to update right in the mods view would maybe be a nice alternative.

I'll have a look at this at some point, as it's quite useful, and a lot better than the current method...
